proxy:
  port: 3838
  authentication: none
  hide-navbar: true
  template-path: ./templates
  landing-page: /app/dashboard
  docker:
      internal-networking: true
  specs:
  - id: dashboard
    display-name: NM Dashboard
    container-cmd: ["R", "-e", "shiny::runApp('/root/app')"]
    container-image: nm-dashboard
    container-network: dash-net
  - id: beekeep-dashboard
    display-name: Beekeep Dashboard
    container-cmd: ["R", "-e", "shiny::runApp('/root/app')"]
    container-image: beekeep-dashboard
    container-network: dash-net

logging:
  file:
    shinyproxy.log